package asd.group2.bms.util;

public interface AppConstants {

  String DEFAULT_PAGE_NUMBER = "0";
  String DEFAULT_PAGE_SIZE = "30";

  float DEFAULT_INTEREST_VALUE = 0.06f;

  float SAVING_INTEREST_VALUE = 0.04F;

  int FOUR_DIGIT = 10000;
  int SIX_DIGIT = 1000000;
  int MAX_PAGE_SIZE = 50;

  int DEFAULT_TRANSACTION_LIMIT = 50000;
  int MINIMUM_TRANSACTION_LIMIT = 5000;
  int MAXIMUM_TRANSACTION_LIMIT = 50000;

  int MINIMUM_BALANCE = 100;

  Long MAX_STATEMENT_RETRIEVE_MONTHS = 3L;

}
